Repository inbo/camtraptor, pull requests merged in 2023-07, with the labels that each got.

#226 Minor spelling corrections
  R/get_effort.R
  R/get_record_table.R
  vignettes/filter-predicates.Rmd
  vignettes/record-table.Rmd
  vignettes/visualize-deployment-features.Rmd
Labels: documentation, enhancement

#257 Write orcids as https in `write_eml()`
  R/write_eml.R
  man/get_effort.Rd
  man/get_record_table.Rd
  tests/testthat/_snaps/write_eml.md
Labels: EML

#229 224 correct vignette visualization deployment
  R/map_dep.R
  man/map_dep.Rd
  tests/testthat/test-get_n_species.R
  tests/testthat/test-map_dep.R
  vignettes/visualize-deployment-features.Rmd
Labels: documentation

#261 Remove small typo and improve sentence
  tests/testthat/test-check_package.R
  vignettes/visualize-deployment-features.Rmd
Labels: documentation
